### ISSUE TITLE
Message Type J

### ISSUE THREAD

**Issue by ChrisPetersen1098** [vgreg/MeatPy#1]
I was trying to parse 07302019.NASDAQ_ITCH50.gz, which is a sample on the NASDAQ ftp site.  It parsed 96million messages and then failed providing the following message:

Exception: ('ITCH50MessageParser:ITCH_factory', 'Unknown message type: J')

I looked up message type J on NASDAQ and it is "Indicates the auction collar thresholds within which a paused security can reopen following a LULD Trading Pause".  

Clearly a rare message.  Any way to get around this issue?

**Comment by vgreg** [comment]
Hi Chris,
Yes, I'm aware of the issue, it's a message type that was added in 2017
after we wrote the code for 5.0. I have a fix almost ready, I'll try to
push it soon.

Best,
Vincent

**Comment by vgreg** [comment]
Hi Chris,
I push the fix to the master branch. I'll try to update the package on pipy this week, but in the meantime you can just get it from the repo.
