### ISSUE TITLE
Messages J and h

### ISSUE THREAD

**Issue by judmejiabe** [vgreg/MeatPy#3]
Is there a reason why message types J and h are excluded from self.keep_messages_types in line 16 of file itch50_message_parser.py? It seems that these messages do not get parsed but they seem to be handled in line 165 of the same file.

Thanks!

**Comment by vgreg** [comment]
That could be an oversight on my part; these message types were added at a later time IIRC. It possible I forgot to add them to the list of messages to parse. I will look into it.

**Comment by vgreg** [comment]
After verification, I forgot to add them to that list when they were added to the specification. They are getting parsed (you can't read an ITCH file without parsing every message), but they are not kept in memory afterward.

I will add time to the next update (no time estimate for this!), but in the meantime, you can add them manually in your code by redefining `keep_messages_types`:

```python
parser = ITCH50MessageParser()
parser.keep_messages_types = b'SAFECXDUBHRYPQINLVWKJh'

with open(sample_dir + 'BX_ITCH_20190530_ALGN.txt', 'rb') as itch_file:
    parser.parse_file(itch_file)
```
